<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ArchivePageContent {
	private $archive_page_content_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'archive_page_content_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'archive_page_content_page_init' ) );
	}

	public function archive_page_content_add_plugin_page() {
		add_submenu_page( 'edit.php?post_type=colective_society', 'Archive Page Content', 'Archive Page Content', 'manage_options', 'colective-society-page-options', array( $this, 'archive_page_content_create_admin_page' ), 1 );
      
		/*add_menu_page(
			'Archive Page Content', // page_title
			'Archive Page Content', // menu_title
			'manage_options', // capability
			'archive-page-content', // menu_slug
			array( $this, 'archive_page_content_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);*/
	}

	public function archive_page_content_create_admin_page() {
		$this->archive_page_content_options = get_option( 'archive_page_content_option_name' ); ?>
         <style>
.page-layout{
    width: 90%;
    margin: auto;
	max-width:1200px;
}
		 </style>
		<div class="page-layout">
			<h2>Archive Page Content</h2>
			<p>Esta es la pagina para la configuraión del contenido de la pagina principal del post tpo de Sociedades Colectivas.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'archive_page_content_option_group' );
					do_settings_sections( 'archive-page-content-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function archive_page_content_page_init() {
		register_setting(
			'archive_page_content_option_group', // option_group
			'archive_page_content_option_name', // option_name
			array( $this, 'archive_page_content_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'archive_page_content_setting_section', // id
			'Settings', // title
			array( $this, 'archive_page_content_section_info' ), // callback
			'archive-page-content-admin' // page
		);

		add_settings_field(
			'titulo_de_la_pagina_0', // id
			'Titulo de la pagina', // title
			array( $this, 'titulo_de_la_pagina_0_callback' ), // callback
			'archive-page-content-admin', // page
			'archive_page_content_setting_section' // section
		);

		add_settings_field(
			'contenido_descriptivo_de_la_pagina_1', // id
			'Contenido descriptivo de la pagina', // title
			array( $this, 'contenido_descriptivo_de_la_pagina_1_callback' ), // callback
			'archive-page-content-admin', // page
			'archive_page_content_setting_section' // section
		);
	}

	public function archive_page_content_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['titulo_de_la_pagina_0'] ) ) {
			$sanitary_values['titulo_de_la_pagina_0'] =  $input['titulo_de_la_pagina_0'] ;
		}

		if ( isset( $input['contenido_descriptivo_de_la_pagina_1'] ) ) {
			$sanitary_values['contenido_descriptivo_de_la_pagina_1'] =  $input['contenido_descriptivo_de_la_pagina_1'] ;
		}

		return $sanitary_values;
	}

	public function archive_page_content_section_info() {
		
	}

	public function titulo_de_la_pagina_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="archive_page_content_option_name[titulo_de_la_pagina_0]" id="titulo_de_la_pagina_0" value="%s">',
			isset( $this->archive_page_content_options['titulo_de_la_pagina_0'] ) ? esc_attr( $this->archive_page_content_options['titulo_de_la_pagina_0']) : ''
		);
	}

	public function contenido_descriptivo_de_la_pagina_1_callback() {
		
		$args = array(
            'wpautop'=>true,
            'media_buttons' => true, // This setting removes the media button.
            'textarea_name' =>'archive_page_content_option_name[contenido_descriptivo_de_la_pagina_1]', // Set custom name.
            'textarea_rows' => 5, //Determine the number of rows.
            'quicktags' => true, // Remove view as HTML button.
        );
        wp_editor( isset( $this->archive_page_content_options['contenido_descriptivo_de_la_pagina_1'] ) ?  $this->archive_page_content_options['contenido_descriptivo_de_la_pagina_1']: '', 'contenido_descriptivo_de_la_pagina_1',  $args );
	}

}
if ( is_admin() )
	$archive_page_content = new ArchivePageContent();

/* 
 * Retrieve this value with:
 * $archive_page_content_options = get_option( 'archive_page_content_option_name' ); // Array of All Options
 * $titulo_de_la_pagina_0 = $archive_page_content_options['titulo_de_la_pagina_0']; // Titulo de la pagina
 * $contenido_descriptivo_de_la_pagina_1 = $archive_page_content_options['contenido_descriptivo_de_la_pagina_1']; // Contenido descriptivo de la pagina
 */
